# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Theory Parking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parking
	pod 'BulletinBoard'
	pod 'Siren'
	pod 'Alamofire'
	pod 'SwiftMessages'
	pod 'lottie-ios'
   	pod 'EmptyDataSet-Swift'
	pod 'GoogleMaps'
	pod 'GooglePlaces'
	pod 'Firebase'
	pod 'Firebase/Core'
  	pod 'Firebase/Auth'
  	pod 'Firebase/Firestore'
	pod 'Firebase/Analytics'
  	pod 'Firebase/Storage'
	pod 'Firebase/Messaging'
   	pod 'Firebase/Functions'
	pod 'Crashlytics'
	pod 'Fabric'
	pod 'Stripe'
	pod 'SwiftyJSON'
	pod 'ZendeskSDK'
end
